[package]
name = "radio-s2lp"
description = "Driver for the ST S2-LP Sub 1GHz ISM band radio IC"
version = "0.1.0"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]

[dependencies]
embedded-hal = { version = "*", features = ["unproven"] }
nb = "0.1.1"
radio = "*"
